modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/OakPlatinum/structure_saplings/issues"
license = "MIT"

[[mods]]
modId = "structure_saplings"
version = "${version}"
displayName = "Structure Saplings"
authors = "Oak Platinum"
description = '''
A server-side, vanilla-friendly, multiplatform, lightweight mod which makes saplings grow into a specific structure!
'''
#logoFile = ""

[[dependencies.structure_saplings]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.structure_saplings]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.structure_saplings]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "structure_saplings.mixins.json"
